--중복은가능,빈값은안됨. NOT NULL / 중복X UNIQUE /유일한값 PRIMARY KEY / 다른테이블과 관계맺기 FOREIGN KEY / 데이터 형태 범위 설정 CHECK / 값을 지정해서 기본값 셋팅 DEFAULT 

--<NOT NULL> 
CREATE TABLE TABLE_NOTNULL(LOGIN_ID VARCHAR(20) NOT NULL, LOGING_PWD VARCHAR(20) NOT NULL, TEL VARCHAR(20) );
SELECT * FROM TABLE_NOTNULL;
DESC TABLE_NOTNULL;
INSERT INTO TABLE_NOTNULL (LOGIN_ID, LOGING_PWD, TEL) VALUES ('TEST_ID_01', '1234','44545-5454' );
ALTER TABLE TABLE_NOTNULL MODIFY(TEL NOT NULL); 


--<제약조건 살펴보기 및 이름 지정>
SELECT * FROM USER_CONSTRAINTS;
CREATE TABLE TABLE_NOTNULL2(LOGIN_ID VARCHAR2(20) CONSTRAINT TBLNN2_LGNID_NN NOT NULL, LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLNN2_LGNPW_NN NOT NULL, TEL VARCHAR2(20)); 
SELECT * FROM USER

-- <UNIQUE > : 중복X,NULL은 가능 
CREATE TABLE TABLE_UNIQUE(LOGIN_ID VARCHAR2(20) UNIQUE, LOGIN_PWD VARCHAR2(20) NOT NULL, TEL VARCHAR2(20));
INSERT INTO TABLE_UNIQUE VALUES ('TEST_ID_01', 'PW01', '010-1234-5678');
INSERT INTO TABLE_UNIQUE VALUES ('TEST_ID_02', 'PW01', '010-1234-5678');
INSERT INTO TABLE_UNIQUE VALUES ('', '1234', '010-1234-5678'); --ID같은경우 UNIQUE 설정하면 중복은 안되지만 NULL값은 적용되서 공백이 가능,, ID가 없는게 말이안되니 ID 공백없게만들잣 

CREATE TABLE TABLE_UNIQUE2(LOGIN_ID VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNID_UNQ UNIQUE, LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLUNQ2_LGNPW_UNQ NOT NULL, TEL VARCHAR2(20)); --제약조건 이름지정
UPDATE TABLE_UNIQUE SET TEL=NULL; --TEL모두 NULL값 설정
ALTER TABLE TABLE_UNIQUE MODIFY( TEL UNIQUE); --이미 존재하는 테이블 열에 유니크 조건 추가(=수정) 
DESC TABLE_UNIQUE;

ALTER TABLE TABLE_UNIQUE2 MODIFY(TEL CONSTRAINT TBLUNQ_TEL_UNQ UNIQUE); --TEL에 제약조건 유니크 걸고 이름지정함. 
SELECT * FROM USER_CONSTRAINTS;
ALTER TABLE TABLE_UNIQUE2 RENAME CONSTRAINT TBLUNQ_TEL_UNQ TO TBLUNQ2_TEL_UNQ;  --TEL 유니크 제약조건 이름 TBLUNQ_TEL_UNQ 에서 TBLUNQ2_TEL_UNQ로 수정 
--제약조건삭제는 DROP CONSTRAINT

--< PRIMARY KEY 유일한값 > : 중복.NULL모두안됨. 주민번호,아이디,사번,학번등에 부여.테이블마다 하나만지정가능 PK만들면 인덱싱 자동만들어짐. 
CREATE TABLE TABLE_PK(LOGIN_ID VARCHAR2(20) PRIMARY KEY, LOGIN_PWD VARCHAR2(20) NOT NULL, TEL VARCHAR2(20) );
DESC TABLE_PK;
SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_INDEXES;
CREATE TABLE TABLE_PK2( LOGIN_ID VARCHAR2(20) CONSTRAINT TBLPK2_LGNID_PK PRIMARY KEY, LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLPK2_LGNPW_NN NOT NULL, TEL VARCHAR2(20) ); --제약조건이름생성 

INSERT INTO TABLE_PK VALUES('TEST_ID_01','PWD01','010-1234-5678');
SELECT * FROM TABLE_PK;   --' ' 빈칸은 NULL로인식안함..

--< FOREIGN KEY > : 다른테이블과 관계맺기 , 참조해올 테이블이 데이터가 없으면 연결안됨 
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME IN('EMP','DEPT');

CREATE TABLE DEPT_FK(DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY, DNAME VARCHAR2(14), LOC VARCHAR2(13));
SELECT * FROM DEPT_FK;
CREATE TABLE EMP_FK( EMPNO NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY, ENANE VARCHAR2(10), JOB VARCHAR2(9), MGR VARCHAR2(4), HIREDATE DATE, SAL NUMBER(7,2), COMM NUMBER(7,2), DEPTNO NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO) );
INSERT INTO DEPT_FK VALUES ( 10, 'TEST_DNAME', 'TEST_LOC' ); --참조해올 테이블 데이터 삽입 
INSERT INTO EMP_FK VALUES ( 9999, 'TEST_ENAME', 'TEST_JOB', NULL, TO_DATE('2025/06/04', 'YYYY/MM/DD'), 3000, NULL, 10) ; --데이터 삽입 
SELECT * FROM EMP_FK;
CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO) ON DELETE CASCADE;   -- 열데이터 삭제시 참조하고있는데이터도 삭제 
CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK(DEPTNO) ON DELETE SET NULL; --열데이터 삭제시 참조하고있는 데이터를 NULL로 수정 

-- < CHECK > : 데이터 형태와 범위 정함.조건값설정  
CREATE TABLE TABLE_CHECK(LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY, LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLCK_LOGINPW_CK CHECK (LENGTH(LOGIN_PWD) > 3), TEL VARCHAR2(20)); --3이상의 PW입력하는 조건에 제약조건검. 
SELECT * FROM TABLE_CHECK;
INSERT INTO TABLE_CHECK VALUES ('TEST_ID', '1234', '010-2012-7536');  



--<DEFAULT> : 기본값을 설정할수 있다 
CREATE TABLE TABLE_DEFAULT (LOGIN_ID VARCHAR2(20) CONSTRAINT TBLCK2_LOGINID_PK PRIMARY KEY, LOGIN_PWD VARCHAR2(20) DEFAULT '0000', TEL VARCHAR2(20) ); --PW를 기본값 0000으로설정. 
INSERT INTO TABLE_DEFAULT (LOGIN_ID, TEL) VALUES ('TEST_ID2', '010-2012-7536' ); --PW를 비워뒀더니 알아서 0000으로 기본값들어감. 
SELECT * FROM TABLE_DEFAULT; 

--<제약조건 비활성화, 활성화> : 제약조건을  활성,비활성 일시적으로 푸는것 가넝.  무결성을 지키면서 유연한 데이터 처리
ALTER TABLE TABLE_DEFAULT DISABLE CONSTRAINT TBLCK2_LOGINID_PK;  --비활성화  
ALTER TABLE TABLE_DEFAULT ENABLE CONSTRAINT TBLCK2_LOGINID_PK; --활성화 
SELECT * FROM USER_CONSTRAINTS; --STATUS 테이블에 보면 ENABLED OR  DISABLE 구분 확인 가능 

------------------------------------------------------------------------------------------------------------

CREATE TABLE DEPT_CONST (DEPTNO NUMBER(2) CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY, DNAME VARCHAR2(14) CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE , LOC VARCHAR2(13) CONSTRAINT DEPTCONST_LOC_NN NOT NULL);
CREATE TABLE EMP_CONST (EMPNO NUMBER(4) CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY, ENAME VARCHAR2(10) CONSTRAINT EMPCONST_ENAME_NN NOT NULL , JOB VARCHAR2(9), TEL VARCHAR2(20) CONSTRAINT EMPCONST_TEL_UNQ UNIQUE, HIREDATE DATE, 
SAL NUMBER(7,2) CONSTRAINT EMPCONST_SAL_CHK CHECK (SAL BETWEEN 1000 AND 9999 ), COMM NUMBER(7,2) , DEPTNO NUMBER(2) CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST (DEPTNO)  );

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME IN ( 'EMP_CONST', 'DEPT_CONST' ) ORDER BY CONSTRAINT_NAME; --데이터사전뷰로 제약조건 확인하기


SELECT * FROM EMP_CONST ; 
DESC DEPT_CONST;